CONFIG_NFCT_PINS_AS_GPIOS=y

## Rotary Encoder ##
# references: https://zmk.dev/docs/config/encoders
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

## Battery Reporting ##
# references: https://zmk.dev/docs/config/battery
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

## Xiao LED ##
# references: https://github.com/caksoylar/zmk-rgbled-widget?tab=readme-ov-file#configuration-details
CONFIG_RGBLED_WIDGET=y
CONFIG_RGBLED_WIDGET_INTERVAL_MS=500
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_HIGH=60
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_LOW=30
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_CRITICAL=10

# === Bluetooth遅延改善設定 ===

# 1. Bluetoothの送信出力を最大(+8dBm)にする
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# 2. 実験的なBLE接続設定を有効化
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
